FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server.py .
COPY finance_app_pb2.py .
COPY finance_app_pb2_grpc.py .

ENV PYTHONUNBUFFERED=1

CMD ["python", "server.py"]