# Usa un'immagine base di Python
FROM python:3.8-slim

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file di requirements e installa le dipendenze
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia il resto del codice dell'applicazione
COPY . .

# Comando di avvio
CMD ["python", "data_collector.py"]