apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: web
    - protocol: TCP
      port: 9100
      targetPort: 9100
      name: datacollector
    - protocol: TCP
      port: 9200
      targetPort: 9200
      name: server
  selector:
    app: prometheus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yaml
              subPath: prometheus.yaml
          command: ["prometheus", "--config.file=/etc/prometheus/prometheus.yaml"]
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ["localhost:9090"]
      - job_name: 'datacollector'
        static_configs:
        - targets: ["datacollector:9100"]
      - job_name: 'server'
        static_configs:
        - targets: ["server:9200"]