---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
    - port: 50051
      name: grpc
    - port: 9200
      targetPort: 9200
      name: prometheus
  selector:
    app: server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: ${IMAGE_REPO}/server-app:latest
          env:
            - name: MYSQL_HOST
              value: mysqldb
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: finance_app
            - name: MYSQL_USER
              value: server
            - name: MYSQL_PASSWORD
              value: "1234"
          ports:
            - containerPort: 50051
      restartPolicy: Always
